version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis
    command: sh redis-script/redis-backup.sh
    volumes:
      - ./redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf